server:
  port: 8080
spring:
  profiles:
    active: "dev"
  application:
    name: Ecomvass
  flyway:
    enabled: true
    user: ${BBDD_USER}
    password: ${BBDD_PWD}
    schemas: ecomvass_schema
    url: jdbc:h2:mem:ecomvass
    locations: classpath:db.migration
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:ecomvass
    driverClassName: org.h2.Driver
    username: ${BBDD_USER}
    password: ${BBDD_PWD}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha